#!/usr/bin/env python3
# Independent SRP-6a (Apple pair-setup flavour) reference to produce a
# known-answer vector for tests/host/test_srp.c:
#   python3 tests/host/gen_srp_kat.py > tests/host/srp_kat.h
import hashlib

N = int(
    "FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74"
    "020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F1437"
    "4FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED"
    "EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3DC2007CB8A163BF05"
    "98DA48361C55D39A69163FA8FD24CF5F83655D23DCA3AD961C62F356208552BB"
    "9ED529077096966D670C354E4ABC9804F1746C08CA18217C32905E462E36CE3B"
    "E39E772C180E86039B2783A2EC07A28FB5C55DF06F4C52C9DE2BCBF695581718"
    "3995497CEA956AE515D2261898FA051015728E5A8AAAC42DAD33170D04507A33"
    "A85521ABDF1CBA64ECFB850458DBEF0A8AEA71575D060C7DB3970F85A6E1E4C7"
    "ABF5AE8CDB0933D71E8C94E04A25619DCEE3D2261AD2EE6BF12FFA06D98A0864"
    "D87602733EC86A64521F2B18177B200CBBE117577A615D6C770988C0BAD946E2"
    "08E24FA074E5AB3143DB5BFCE0FD108E4B82D120A93AD2CAFFFFFFFFFFFFFFFF",
    16)
g = 5
H = lambda *parts: hashlib.sha512(b"".join(parts)).digest()
i2b = lambda n, l=None: n.to_bytes(l if l else max(1, (n.bit_length() + 7) // 8), "big")
b2i = lambda b: int.from_bytes(b, "big")

I, P = b"Pair-Setup", b"3939"
salt = bytes(range(0xA0, 0xB0))
b = b2i(bytes((7 * i + 3) & 0xFF for i in range(32)))
a = b2i(bytes((11 * i + 5) & 0xFF for i in range(32)))

k = b2i(H(i2b(N, 384), i2b(g, 384)))
x = b2i(H(salt, H(I + b":" + P)))
v = pow(g, x, N)
B = (k * v + pow(g, b, N)) % N
A = pow(g, a, N)
u = b2i(H(i2b(A, 384), i2b(B, 384)))
# client side
S_c = pow((B - k * v) % N, a + u * x, N)
# server side
S = pow(A * pow(v, u, N) % N, b, N)
assert S == S_c
K = H(i2b(S))
hng = bytes(p ^ q for p, q in zip(H(i2b(N)), H(bytes([g]))))
M1 = H(hng, H(I), salt, i2b(A), i2b(B), K)
M2 = H(i2b(A), M1, K)


def carr(name, data):
    s = "static const uint8_t %s[%d] = {\n" % (name, len(data))
    for i in range(0, len(data), 12):
        s += "    " + ", ".join("0x%02x" % c for c in data[i:i + 12]) + ",\n"
    return s + "};\n"


print("// Generated by tests/host/gen_srp_kat.py (independent Python SRP-6a).")
print(carr("kat_salt", salt))
print(carr("kat_b", i2b(b, 32)))
print(carr("kat_A", i2b(A, 384)))
print(carr("kat_B", i2b(B, 384)))
print(carr("kat_M1", M1))
print(carr("kat_M2", M2))
print(carr("kat_K", K))
