#!/usr/bin/env python3
"""Generate the firmware audio-profile header from a small JSON file."""

import argparse
import json
from pathlib import Path


REQUIRED = (
    "name",
    "airplay_min_db",
    "airplay_mid_db",
    "airplay_max_db",
    "output_min_db",
    "output_mid_db",
    "output_max_db",
    "bass_shelf_db",
    "bass_shelf_hz",
)


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "profile",
        nargs="?",
        default=repo / "audio_profiles" / "pcm5102-a1s.json",
        type=Path,
    )
    args = parser.parse_args()

    data = json.loads(args.profile.read_text())
    missing = [key for key in REQUIRED if key not in data]
    if missing:
        raise SystemExit(f"Missing profile fields: {', '.join(missing)}")

    output = repo / "main" / "audio" / "audio_output_profile_config.h"
    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/apply_audio_profile.py. Do not edit directly.",
        f'#define AUDIO_PROFILE_NAME "{data["name"]}"',
    ]
    for key in REQUIRED[1:]:
        macro = f"AUDIO_PROFILE_{key.upper()}"
        lines.append(f"#define {macro} {float(data[key]):.6f}f")
    lines.append("")
    output.write_text("\n".join(lines))
    print(f"Generated {output.relative_to(repo)} from {args.profile}")


if __name__ == "__main__":
    main()
